networks:
  arrnet:
    name: arrnet
    ipam:
      config:
        - subnet: 10.0.0.0/22

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/config/jellyfin:/config
      - /data/media/shows:/data/tv
      - /data/media/movies:/data/movies
    networks:
      arrnet:
        ipv4_address: 10.0.0.1 
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
    volumes:
      - /data/config/jellyseerr:/app/config
    networks:
      arrnet:
        ipv4_address: 10.0.0.2 
    ports:
      - 5055:5055
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/config/radarr:/config
      - /data/media/movies:/movies #optional
      - /data/downloads:/downloads
    networks:
      arrnet:
        ipv4_address: 10.0.1.1 
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/config/sonarr:/config
      - /data/media/shows:/tv #optional
    networks:
      arrnet:
        ipv4_address: 10.0.1.2 
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/config/prowlarr:/config
    networks:
      arrnet:
        ipv4_address: 10.0.1.3 
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /data/config/qbittorrent:/config
      - /data/downloads/torrents:/downloads
    networks:
      arrnet:
        ipv4_address: 10.0.2.1 
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
 
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - NZBGET_USER=nzbget #optional
      - NZBGET_PASS=tegbzn6789 #optional
    volumes:
      - /data/config/nzbget:/config
      - /data/downloads/nzb:/downloads
    networks:
      arrnet:
        ipv4_address: 10.0.2.2 
    ports:
      - 6789:6789
    restart: unless-stopped

